name = "verfication_module"
main = "./src/index.js"
compatibility_date = "2023-02-06"
# [env.staging]
# kv_namespaces = [{ binding = "VERIFICATION_TOKENS", preview_id = "679bd5c734ac4707a687876b9439a249" }]


[env.staging]
[[kv_namespaces]]
binding = "VERIFICATION_TOKENS"
preview_id = "679bd5c734ac4707a687876b9439a249"
id = "679bd5c734ac4707a687876b9439a249"

NEPTUNE_ENV="dev"
NEPTUNE_TOKEN="eyJhbGciOiJFZERTQSJ9.eyJleHAiOjE3MDc4Mjg2MzcsInN1YiI6ImFkMmExMDg3LTY5ODktNGNkYi05ZDkwLTAzYWM1OGFkYTYyYiIsImlzcyI6InRlYW0iLCJqdGkiOiI3NWEwNWRiOC1kNjNiLTRlMTctYTk5NC05ZTFjNGJlODUyMGEifQ.iQVbJwb7y2RtZ0pY_xWUQGt6qLuzeml58aBXaR89RRc61-AWRw6UqCBz0fWHuaNQkDfhRYvBcnCdb0p1WhSjBQ"

[build]
command = "npm run build"